# Generated by Django 4.1.4 on 2022-12-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action',
            field=models.CharField(choices=[('goal', 'Goal'), ('assist', 'Assist'), ('yellow card', 'Yellow Card'), ('red card', 'Red Card')], max_length=50),
        ),
    ]
