services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cartola
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    ulimits:
      # https://github.com/docker-library/mysql/issues/579#issuecomment-1075119349
      nproc: 65535
      nofile:
        soft: 26677
        hard: 46677

  goapp:
    depends_on:
      - mysql
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/go/app
    platform: linux/amd64
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
